### ISSUE TITLE
Improve the usability of the controlpanel

### ISSUE THREAD

**Issue by xn--nding-jua** [xn--nding-jua/PC_DIMMER#1]
- Add a new row
- Drag&Drop
- general usability

**Comment by SLJ-Coding** [comment]
Bitte auch einbauen das man Zeilen verschieben kann und ganz löschen.
Über den Einbau einer Auswahl für verschiedene Ebenen wie bei der Bühnenansicht würde ich doch mal nachdenken bzw. das man mehrere öffnen kann.

**Comment by xn--nding-jua** [comment]
Zeilen verschieben ist recht einfach zu implementieren. Ganz löschen ist dann auch kein größeres Problem, sobald ich die Verschiebe-Funktion implementiert habe. Ich muss mir halt mal überlegen, wie man recht einfach die Bedienung/Darstellung dieses Editiermodus umsetzt.

Das gesamte Kontrollpanel wird von mir selbst gezeichnet. Somit existieren keine Buttons, sondern die Oberfläche wird selbst gezeichnet. Somit ist es relativ viel Aufwand, so Drag&Drop-Funktionen einzubauen, da ich nicht auf die Windows-Standardfunktionen zurückgreifen kann.

Mal sehen, was ich tun kann. Es wird aber vermutlich nichts mehr für v5.4.2 :-/

**Comment by xn--nding-jua** [comment]
So, folgendes ist implementiert:
- neue Reihe einfügen
- Reihe löschen
- Reihe nach unten oder oben verschieben
- Drag&Drop implementiert (war leichter als befürchtet _g_)
