### ISSUE TITLE
DDF Editor

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#23]
Beim erstellen von Gerätefarben(Color1) kann man mit Tab nicht von Startwert zu Endwert Springen.

Den Endwert könnte man als Startwert +1 nehmen.

Wenn man einen Farbwert erstellt ( + ) könnte der Cursor gleich in das Eingabe Feld Springen.

Das Kanal Fading für Color 1 und 2 sollte man Standard mäßig Deaktivieren. (Hinweis steht aber dabei!! Wer nicht lesen kann ist selbst Schuld (Habe die halbe Nacht damit verbracht es nicht zu lesen)  )

Das verschieben von Objekten mit den Pfeiltasten dauert Ewig (Komisches Verzögerungs ruckeln) keine Ahnung ob man da was Verbessern kann finde das verschieben mit Tastatur recht Praktisch. 

Kann man nicht auch paar Kanaltypen löschen gobo1rot, gobo2rot und prismarot, finde das ganze bisschen unübersichtlich mittlerweile. Oder 2 listen erstellen einmal normale und die meisten sind ja für Scanner, Moving Heads nur so eine Idee, DDF's erstellt man ja nicht so häufig. 

mfg
Stefan

**Comment by SLJ-Coding** [comment]
Oh magst du lieber pro Eintrag einen Fehler/Verbesserung/Wunsch wegen der Übersichtlichkeit ?

**Comment by SLJ-Coding** [comment]
Kanaltypen sollte man nicht umbenenne dürfen denke ich zumindest ?!?!

**Comment by SLJ-Coding** [comment]
Hier mal die Datei er zeigt "Farbe 1" an aber ich habe Blackout und Rot definiert. Direkt aus dem Editor.
[Eurolite FE-600.zip](https://github.com/xn--nding-jua/PC_DIMMER/files/75564/Eurolite.FE-600.zip)

Edit: Hab's hinbekommen es fehlt unter anderem  procedure COLOR1change;

**Comment by xn--nding-jua** [comment]
Einige Änderungen übernommen. -> closed
