### ISSUE TITLE
Kontrollpanel,...

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#27]
...vergisst häufig das ich die Bilder anzeigen Deaktiviert habe. Und welche Breite ich eingestellt habe  auch die Eingabe ist komisch da er sich weigert mehr wie 500 einzugeben und weniger wie 25,... so kann ich nicht einfach 80 einstellen außer mit hoch und runter. 

Ich Wünsche dir ein Gutes neues Jahr (nutze gerade die Software fürs die Party)

**Comment by SLJ-Coding** [comment]
Beim verschieben wird auch der Button Text z.b. Button 15 X 7 verschoben.  An eine völlig falsche Position.

**Comment by xn--nding-jua** [comment]
Folgende Dinge wurden implementiert:
- Minimale Buttonbreite: nun 15 statt 25 Pixel
- Maximale Anzahl an Buttons von 50 auf 99 erhöht

Nicht veränderte Dinge:
- Verschieben des Textes muss so bleiben. Evtl. wollte der Nutzer das ja so. Lediglich die initiale Bezeichnung lautet "Button X x Y". Was der Nutzer danach macht ist seine Sache.

Einstellung, ob Bilder angezeigt werden sollen wird korrekt beim Schließen des Fensters in die Registry geschrieben. Ich kann hier keinen Fehler finden.

Closed.
