### ISSUE TITLE
Geräteszenen Editor

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#29]
Bei einzelnen Geräten zeigt er die tatsächlichen definierten Kanäle an. Bei gruppen alle Kanäle die man wählen kann leider fehlen einige, bzw. die umbenannten sind unter gruppen nicht zu finden.

mfg
Stefan

**Comment by xn--nding-jua** [comment]
Gruppen besitzen keine DDFs aus denen man die Namen herauslesen könnte. Somit werden die generischen Kanalnamen angezeigt. Leider nicht zu ändern -> closed
