### ISSUE TITLE
Befehls System 

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#30]
Wollte einen neuen Befehl anlegen dann kam "Das Fenster hat keine Bildlaufleisten." dann weggeklickt Szenenverwaltung geschlossen und es geht wieder. Fehler kommt ab und zu aber nicht nachvollziehbar für mich. Es kommt auch ab und zu beim Bearbeiten eines Befehls.

mfg
Stefan

**Comment by xn--nding-jua** [comment]
Leider auch für mich nicht nachvollziehbar -> closed
