### ISSUE TITLE
Kombinationsszene

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#31]
Ständig die Meldung "Bitte stellen Sie sicher, dass der Befehl....." nervt :(

**Comment by SLJ-Coding** [comment]
Man kann nur 10 Kombi Szenen zusammen fügen bei mehr gibst eine Zugriffsverletzung. Nach den 10 zeigt er nur ... an. Ich schaue dennoch ob's geht.

Edit: Ich habe das Programm neu gestartet jetzt scheint es zu gehen.

**Comment by xn--nding-jua** [comment]
`"Bitte stellen Sie sicher, dass der Befehl....." nervt :(`

Nervt, ja, aber mit Kombinationsszenen kann man sich seine Projekte tatsächlich erfolgreich kaputt machen und sollten nur selten eingesetzt werden. Somit bleibt die Meldung -> closed

**Comment by SLJ-Coding** [comment]
Naja dachte so das wenn ich das Projekt jetzt öffne es einmal kommt und wenn ich das Projekt nochmal öffne darf es nochmal erscheinen.
