### ISSUE TITLE
Zugriffsverletzungen

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#32]
Beim lesen von Adresse 20424752.

Beim normalen beenden. Egal ob mit oder ohne Speichern er steht bei 20% Senden von Plugins Speichern-Befehl...

**Comment by xn--nding-jua** [comment]
Dieser Fehler tritt nur dann auf, wenn bereits zuvor im Programm ein Fehler aufgetreten war. Somit ist dies ein Folgefehler. Ich werde allerdings versuchen ihn hier abzufangen, damit man das Programm dennoch beenden kann.

**Comment by xn--nding-jua** [comment]
Habe es mir angesehen -> Fehlerweg und -verhalten ist im Fehlerfall nicht wirklich nachvollziehbar -> closed
