### ISSUE TITLE
Grafische Bühnenansicht

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#35]
Kann man einbauen das pro Feld nur 1 gerät möglich ist. Außer beim hinzufügen neuen Geräten.

**Comment by xn--nding-jua** [comment]
Das führt vermutlich zu ungewolltem Verhalten der Icons, da sich dann ja die Icons gegenseitig wegschieben können müssen. Es ist ja bereits die Option "ALT + Drag&Drop" implementiert, sodass man die Icons automatisch an einer Kette hängend verteilen kann. Das sollte beim Einrichten helfen.

Fügt man mehrere Icons hinzu, werden diese auch automatisch nebeneinander angeordnet.

Somit werde ich diese Option nicht einbauen.
