### ISSUE TITLE
Szenenverwaltung

### ISSUE THREAD

**Issue by ghost** [xn--nding-jua/PC_DIMMER#39]
Wenn neue Szenen in der Szenenverwaltung erstellt oder kopiert werden, sortiert PC-Dimmer die Szenen alphabetisch.
Wenn die Szenen einer Kategorie zugeordnet werden, sortiert PC-Dimmer zwar die Kategorien alphabetisch, aber die Szenen in den Kategorieen werden nach dem Zeitpunkt des erstellens sortiert.

Gibt es eine Möglichkeit, diese auch alphbetisch zu sortieren?

**Comment by xn--nding-jua** [comment]
Welche Version des PC_DIMMERs nutzt Du? Ich dachte ich hätte das in Version 5.4.3 korrigiert?

**Comment by ghost** [comment]
Bei mir stürtzt das Programm ab, wenn ich "Alle Effekte Beenden" ausführe.
Siehe https://github.com/xn--nding-jua/PC_DIMMER/issues/34

Daher bin ich noch auf Version 5.1.4.4571, da dort das Programm beim Ausführen von "Alle Effekte Beenden" nicht abstürzt.

wenn das ab Version 5.4.3 korrigiert ist, hat sich meine Frage erledigt.

**Comment by xn--nding-jua** [comment]
Gut, dann schaue ich mir zunächst den Fehler bei den Effekten noch einmal an :)

**Comment by ghost** [comment]
Danke :)

**Comment by xn--nding-jua** [comment]
Sortierung in Szenenverwaltung ist in neuer Version OK. Absturzproblem wird in anderem Issue behandelt.

Closed.
