### ISSUE TITLE
LED-Scheinwerfer ohne Dimmer --> virtueller Dimmer

### ISSUE THREAD

**Issue by ghost** [xn--nding-jua/PC_DIMMER#50]
Manche LED-Scheinwerfer besitzen keinen Dimmerkanal, über den die Helligkeit nachträglich gesteuert werden kann.
Mithilfe des Master-Dimmer-Faders kann man die LED-Scheinwerfer ohne eigenen Dimmer-Kanal dimmern, jodoch werden dann auch alle anderen Scheinwerfer dunkler.

Ist es möglich einen Virtuellen Dimmer zu realisieren, über den LED-Scheinwerfer ohne eigenen Dimmer-Kanal gedimmt werden können, ohne dass dabei die anderen Scheinwerfer dunkler werden.

**Comment by xn--nding-jua** [comment]
Hi,

so eine Funktion ist bereits implementiert. Schau Dir mal das Gerät "Generic_RGBVDScheinwerfer.pcddevc" als Beispiel im "Devices"-Ordner an.
