### ISSUE TITLE
Lauflichtassistent & Matrixeditor

### ISSUE THREAD

**Issue by ghost** [xn--nding-jua/PC_DIMMER#51]
Über den Lauflichtassistent und Matrixeditor lassen sich sehr bequem Lauflichter bzw. Matrixen realisieren, bei denen für jeden Schritt eine Geräteszene erstellt wird.
Diese Geräteszene ist allerdings nicht in der Kategorie Geräteszene gelistet.

Kann man diese Geräteszenen in der Kategorie "Geräteszenen" auflisten?
Könnte man diese dann anschließend auch mit dem Matrixeditor überarbeiten/ergänzen (https://github.com/xn--nding-jua/PC_DIMMER/issues/49)?

**Comment by xn--nding-jua** [comment]
Um die Übersichtlichkeit in der Szenenverwaltung nicht zu strapazieren, habe ich mich dazu entschieden, Effektszenen und Direktszenen aus dem Audioeffektplayer nicht in die Szenenverwaltung aufzunehmen. Andernfalls würden hunderte Einzelszenen für Lauflichter ebenfalls dort aufgelistet werden. Da die Szenen zudem derzeit nicht nur nicht angezeigt, sondern auch in völlig anderen Speicherbereichen liegen, ist eine Anzeige unter der Szenenverwaltung nicht ohne große Änderungen möglich.

Eine Bearbeitung von Szenen im Matrixeditor ist leider nicht möglich, da die Zuordnungsinfos der einzelnen Kanäle zu den Matrix-Kästchen nicht in den Szenen abgespeichert wird. Somit ist dies nicht möglich und kann auch nicht programmiert werden.
