### ISSUE TITLE
Masterdimmer, virtuelle Dimmer und W, UV, CMY

### ISSUE THREAD

**Issue by digitalshow** [xn--nding-jua/PC_DIMMER#52]
- Dimmer-, R-, G- und B-Kanäle werden einzeln richtig mit Masterdimmer und eventuell vorhandenem virtuellem Dimmerkanal beaufschlagt. W-, UV-, YELLOW-, CYAN-, und MAGENTA-Kanäle werden nicht berücksichtigt. W- und UV-Kanäle werden gehindert an [Zeile 2678](https://github.com/xn--nding-jua/PC_DIMMER/commit/5fef36de33d708bc602abed24c8b870885273287#diff-0dbb51d5dfbb29092081465349ebc214R2678) und [Zeile 2839](https://github.com/xn--nding-jua/PC_DIMMER/commit/5fef36de33d708bc602abed24c8b870885273287#diff-0dbb51d5dfbb29092081465349ebc214R2839) in pcdimmer.pas. CMY-Kanäle werden momentan gar nicht berücksichtigt. In der Regel wurden diese vermutlich mit MHs verwendet, die sowieso einen Dimmerkanal haben. Durch LED-Scheinwerfer wird der YELLOW-Kanal nun auch ohne Dimmer oder mit virtuellem Dimmer genutzt. 
- Dabei fällt auf, dass R-, G-, B- und A-Kanäle bei tatsächlich vorhandenem Dimmer zusätzlich zum Dimmerkanal mit dem Masterdimmer beaufschlagt werden.

**Comment by xn--nding-jua** [comment]
Behoben.
