### ISSUE TITLE
Geräteszene (Zufällig)

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#55]
Wenn ich eine Geräte Scene auf "Zufällig" stelle will muss ich erst "Aktiviert" auswählen.

Wenn ich mehrere ausgewählt habe muss ich aber erst neu Markieren damit der erkennt das diese Jetzt Aktiviert wurden. 

mfg
Stefan

**Comment by xn--nding-jua** [comment]
Behoben
