### ISSUE TITLE
Effekt Verschieben

### ISSUE THREAD

**Issue by SLJ-Coding** [xn--nding-jua/PC_DIMMER#56]
Wenn ich mehrere Effekte Anlege und diese von "Alle" zu einem neu angelegten verschieben möchte muss ich jedes einzeln verschieben, markieren und alle auf einmal verschieben geht er leider nicht bzw. er nimmt es nicht an.

mfg
Stefan

**Comment by xn--nding-jua** [comment]
Behoben.
