### ISSUE TITLE
MIDI

### ISSUE THREAD

**Issue by alexanderbol** [xn--nding-jua/PC_DIMMER#63]
Midi Daten werden bei der Midi Event erstellung richtig angezeigt, nur leider bekomme ich keinen einzigsten kanal / gerät gedimmt, was mir aufgefallen ist das dann in der event übersicht die midi daten nicht mehr richtig dargestellt werden sondern um eine position verschoben ist. kann das der fehler sein?
![pcdimmer_fehler](https://cloud.githubusercontent.com/assets/24324319/20850878/d3e6d604-b8dd-11e6-9b46-8d7e3d033f9c.jpg)

**Comment by digitalshow** [comment]
Die Verschiebung in der Anzeige ist tatsächlich ein Programmfehler. Jedoch hindert dies i. A. nicht die Verarbeitung. Bist du dir sicher, dass du den Wert von Data1 statt von Data2 beziehen willst? In der Regel liegt hier schon der Fehler. Ansonsten solltest du vielleicht erstmal "Geräte / Gruppen" -> "Bestimmtes Gerät auf Eingangswert" ausprobieren. Zu den modusabhängigen Befehlen siehe den [Wiki-Eintrag](https://www.pcdimmer.de/wiki/index.php?title=Tipps_und_Tricks#Ger.C3.A4te_mit_zwei_Tasten_ein-.2Fausblenden.2C_flashen_und_auf_Wert_schalten).

**Comment by xn--nding-jua** [comment]
Ich entferne das "Message, Data1, Data2" in der Titelleiste. Dort steht nämlich nur der tatsächlich ausgewertete MIDI-Wert.

**Comment by alexanderbol** [comment]
Hallo, ok, es wurde glaube ich von dir Falsch verstanden. Ich hab in dem UPdate gesehen, das du die Bezeichnungen raus genommen hast. Aber das war nicht das Problem sondern das wenn ein Midi Signal kommt, er das MSG in die Beschreibungsspalte schreibt, srich die beschreibung überschreibt in der Übersicht! Ist also nur ein darstellungs problem. Gruß
